# Robbie the Robot is built from a left Wheel, a right Wheel and a Head
config:

    # Construct the left Wheel from a Motor, an Encoder and a PID controller...
    leftwheel:
        AFMotor:                        # Adafruit Motor Shield
            motornum: 3                 #  Motor Number 3

        encoder:                        # Encoder for measuring wheel speed
            controlpin: 2               #   Arduino input pin for encoder signal

        pid:                            # A PID feedback controller
            K: [ 0.2, 0.0, 0.0 ]        #   PID params: Kp, Ki, Kd
            range: [ -255, 255]         #   Min and max output values
            sampletime_ms: 200          #   Milliseconds between PID update

    # Construct the right Wheel from a Motor, an Encoder and a PID controller...
    rightwheel:
        AFMotor:                        # Adafruit Motor Shield
            motornum: 4                 #  Motor Number 4

        encoder:                        # Encoder for measuring wheel speed
            controlpin: 3               #   Arduino input pin for encoder signal

        pid:                            # A PID feedback controller
            K: [0.2, 0.0, 0.0]          #   PID params: Kp, Ki, Kd
            range: [-255, 255]          #   Min and max output values
            sampletime_ms: 200          #   Milliseconds between PID update

    # Construct the Head from two servo controllers
    head:
        headX:                          # Servo for left-right rotation
            controlpin: 10              #   Arduino control pin for servo
            range: [18, 68, 116]        #   Min, Centre, Max for servo

        headY:                          # Servo for up-down rotation
            controlpin: 9               #   Arduino control pin for servo
            range: [24, 54, 106]        #   Min, Centre, Max for servo

# Local Variables:
# yaml-indent-offset: 4
# indent-tabs-mode: nil
# End:
