ARDUINO_DIR   = /usr/share/arduino
ARDMK_DIR     = /usr
AVR_TOOLS_DIR = /usr

BOARD_TAG    = pro328
ARDUINO_PORT = /dev/ttyUSB0

ARDUINO_LIBS = 

# default: upload

include /usr/share/arduino/Arduino.mk

